var first = prompt("What is your first name? ")
var last = prompt("What is your last name? ")
var age = prompt("How old are you?")
console.log("Hello "+first+" "+last+"!")
console.log("You are "+age+" years old.")